# Generated by Django 2.2.17 on 2020-12-17 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20201217_0711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtext',
            name='gfdgfdgf',
        ),
        migrations.RemoveField(
            model_name='customtext',
            name='ghfhfhgfg',
        ),
        migrations.RemoveField(
            model_name='customtext',
            name='ghfhgfhgfghf',
        ),
    ]
